#!/bin/sh

# Copyright (C) 2022 Keith "vorble"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -eu

. include/maybe

pre_install_hook() {
    if [ "$KERNEL" = "Linux" -a "$DISTRO" = "CentOS" ]; then
        maybe yum -y groupinstall 'Development Tools'
    fi
}

list_packages() {
    if [ "$KERNEL" = "Linux" -a "$DISTRO" = "Debian" ]; then
        echo "build-essential"
    elif [ "$KERNEL" = "Linux" -a "$DISTRO" = "CentOS" ]; then
        : # This is installed in pre_install_hook.
    elif [ "$KERNEL" = "OpenBSD" ]; then
        if [ "$PLZHELP" != "0" ]; then
            echo "PLZHELP: feature/dev: list_packages() is implemented for OpenBSD, but no packages listed. Do any make sense?" >&2
        fi
    else
        echo "feature/dev: list_packages() is not implemented for KERNEL=$KERNEL DISTRO=$DISTRO" >&2
        exit 1
    fi
}

"${@}"
