#!/bin/bash

set -euo pipefail

function list_apt_packages() {
    if [[ "${HAS_NVIDIA_GRAPHICS}" != "0" ]]; then
        echo "nvidia-driver"
    fi

    if [[ "${HAS_AMD_GRAPHICS}" != "0" ]]; then
        echo "firmware-amd-graphics"
    fi
}

"${@}"
