#!/bin/sh

# Copyright (C) 2022 Keith "vorble"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -eu

list_prerequisites() {
    if [ "$KERNEL" = "Linux" -a "$DISTRO" = "CentOS" ]; then
        echo "feature/centos/epel"
    fi
}

list_packages() {
    if [ "$KERNEL" = "Linux" -a "$DISTRO" = "Debian" ]; then
        echo "libimage-exiftool-perl"
    elif [ "$KERNEL" = "Linux" -a "$DISTRO" = "CentOS" ]; then
        # CentOS Stream 9 does not have this package or an alternative that
        # I've been able to find in May 2022.
        if [ "$DISTRO_VERSION" -lt "9" ]; then
            echo "perl-Image-ExifTool"
        else
            echo "feature/exiftool: list_packages() is not implemented for KERNEL=$KERNEL DISTRO=$DISTRO DISTRO_VERSION=$DISTRO_VERSION" >&2
            exit 1
        fi
    else
        echo "feature/exiftool: list_packages() is not implemented for KERNEL=$KERNEL DISTRO=$DISTRO" >&2
        exit 1
    fi
}

"${@}"
