#!/bin/sh

set -eu

list_packages() {
    if [ "$KERNEL" = "Linux" -a "$DISTRO" = "Debian" ]; then
        if [ "${CPU_VENDOR}" = "intel" ]; then
            echo "intel-microcode"
        elif [ "${CPU_VENDOR}" = "amd" ]; then
            echo "amd64-microcode"
        fi
    fi
}

"${@}"
