#!/bin/sh

# Copyright (C) 2022 Keith "vorble"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -eu

pre_install_hook() {
    if [ "$KERNEL" != "Linux" -o "$DISTRO" != "Debian" ]; then
        echo "feature/non-free: Feature is currently only supported on Debian GNU/Linux." >&2
        exit 1
    fi

    echo apt-get update
    if [ "$DRY_RUN" = "0" ]; then
        apt-get update
    fi
    echo apt-get install --yes software-properties-common
    if [ "$DRY_RUN" = "0" ]; then
        # This install provides the apt-add-repository binary.
        apt-get install --yes software-properties-common
    fi
    echo apt-add-repository contrib
    if [ "$DRY_RUN" = "0" ]; then
        apt-add-repository contrib
    fi
    echo apt-add-repository non-free
    if [ "$DRY_RUN" = "0" ]; then
        apt-add-repository non-free
    fi
}

"${@}"
