#!/bin/sh

# Copyright (C) 2022 Keith "vorble"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -eu

list_packages() {
    if [ "$KERNEL" = "Linux" -a "$DISTRO" = "Debian" ]; then
        echo "tmux"
    elif [ "$KERNEL" = "Linux" -a "$DISTRO" = "CentOS" ]; then
        echo "tmux"
    elif [ "$KERNEL" = "Linux" -a "$DISTRO" = "Fedora" ]; then
        echo "tmux"
    elif [ "$KERNEL" = "Linux" -a "$DISTRO" = "openSUSE" ]; then
        echo "tmux"
    elif [ "$KERNEL" = "OpenBSD" ]; then
        # RESEARCH: Did tmux always come in OpenBSD?
        # Comes by default in 7, don't know about prior versions.
        # If version is less than 7, add tmux as a package just in case.
        if ! $( exit `echo "$DISTRO_VERSION < 7" | bc` ); then
            if [ "$PLZHELP" != "0" ]; then
                echo "PLZHELP: feature/tmux: list_packages(): Does tmux come by default on OpenBSD prior to 7?" >&2
            fi
            echo "tmux"
        fi
    else
        echo "feature/tmux: list_packages() is not implemented for KERNEL=$KERNEL DISTRO=$DISTRO" >&2
        exit 1
    fi
}

"${@}"
