#!/bin/sh

# Copyright (C) 2022 Keith "vorble"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -eu

on_finish() {
    local PLATFORM_STRING="vorble $VORBLE_VERSION $LOADOUT"
    local SETUP_STRING="`date`: $PLATFORM_STRING"
    echo ${PATH_ETC}/platform.vorble: $PLATFORM_STRING
    echo ${PATH_ETC}/setup.log: $SETUP_STRING
    if [ "$DRY_RUN" = "0" ]; then
        echo $PLATFORM_STRING > "${PATH_ETC}/platform.vorble"
        echo $SETUP_STRING >> "${PATH_ETC}/setup.log"
    fi
}

"${@}"
