# This CI pipeline performs tests on GitLab runners configured on GitLab for
# this project.

image: debian:bullseye-slim

before_script:
  - echo "<<< START >>>"

after_script:
  - echo "<<< END >>>"

test_dry:
  stage: test
  script:
    - DRY_RUN=1 USERS="root" ./platform vorble/loadout/base

test:
  stage: test
  script:
    - USERS="root" ./platform vorble/loadout/base

