# This CI pipeline performs tests on GitLab runners configured on GitLab for
# this project.

image: debian:bullseye-slim

before_script:
  - echo "<<< START >>>"

after_script:
  - echo "<<< END >>>"

test1:
  stage: test
  script:
    - ls
