# This CI pipeline performs tests on GitLab runners configured on GitLab for
# this project.

image: debian:bullseye

before_script:
  - echo "<<< START >>>"

after_script:
  - echo "<<< END >>>"

test_check_reference:
  stage: test
  script:
    - apt-get update && apt-get install -y python3
    - ./tool/check_reference.sh

test_vorble_base:
  stage: test
  script:
    # Prevent apt-get from asking for input (setting up the keyboard).
    - export DEBIAN_FRONTEND=noninteractive
    # --gecos "" prevents interactive asking for user info.
    - adduser --gecos "" keith
    - DRY_RUN=1 USERS="root keith" ./platform vorble/loadout/base
    - USERS="root keith" ./platform vorble/loadout/base

test_vorble_dev:
  stage: test
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - adduser --gecos "" keith
    - DRY_RUN=1 USERS="root keith" ./platform vorble/loadout/dev
    - USERS="root keith" ./platform vorble/loadout/dev
