# This CI pipeline performs tests on GitLab runners configured on GitLab for
# this project.

image: debian:bullseye-slim

before_script:
  - echo "<<< START >>>"

after_script:
  - echo "<<< END >>>"

test_vorble_base_dry:
  stage: test
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - adduser keith
    - DRY_RUN=1 USERS="root keith" ./platform vorble/loadout/base

test_vorble_base:
  stage: test
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - adduser keith
    - USERS="root keith" ./platform vorble/loadout/base

test_vorble_dev_dry:
  stage: test
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - adduser keith
    - DRY_RUN=1 USERS="root keith" ./platform vorble/loadout/dev

test_vorble_dev:
  stage: test
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - adduser keith
    - USERS="root keith" ./platform vorble/loadout/dev
