#!/bin/sh

set -eu

# This hook is called as the platform process starts, before any features start
# running.
on_start() {
    # You might clear a directory before proceeding with the set up.
    :
}

# this hook is called as the platform process finishes, after all features are
# finished being set up.
on_finish() {
    # You might send an email to the system administrator with installation
    # details.
    :
}

"${@}"
