#!/bin/sh

set -eu

. include/watermark_add

list_prerequisites() {
    if [ "$ALLOW_NONFREE" != "0" ]; then
        if [ "$KERNEL" = "Linux" -a "$DISTRO" = "Debian" ]; then
            echo "feature/debian/non-free"
        fi
    fi
}

list_features() {
    echo "feature/curl"
    echo "feature/dev"
    echo "feature/drivers"
    echo "feature/firmware"
    echo "feature/gdb"
    echo "feature/rsync"
    echo "feature/screen"
    echo "feature/tmux"
    echo "vorble/feature/vim"

    # TODO: Find these on OpenBSD if possible!
    if [ "$KERNEL" = "Linux" ]; then
        echo "feature/exiftool"
        echo "feature/iotop"
        echo "feature/ltrace"
        echo "feature/silversearcher"
        echo "feature/smartmontools"
        echo "feature/strace"
        echo "vorble/feature/sudo"
        echo "feature/valgrind"
    fi

    if [ "$ALLOW_NONFREE" != "0" ]; then
        if [ "$IS_METAL" != "0" -a "$KERNEL" = "Linux" -a "$DISTRO" = "Debian" ]; then
            echo "feature/zfs"
        fi
    fi
}

post_install_hook() {
    watermark_add "vorble $VORBLE_VERSION"
}

"${@}"
