#!/bin/sh

# Copyright (C) 2022 Keith "vorble"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -eu

list_features() {
    echo "feature/curl"
    echo "feature/dev"
    echo "feature/drivers"
    echo "feature/firmware"
    echo "feature/gdb"
    echo "feature/rsync"
    echo "feature/screen"
    echo "feature/tmux"
    echo "vorble/feature/vim"

    if [ "$KERNEL" = "Linux" ]; then
        echo "feature/iotop"
        echo "feature/ltrace"
        echo "feature/silversearcher"
        echo "feature/smartmontools"
        echo "feature/strace"
        echo "vorble/feature/sudo"
        echo "feature/valgrind"
    fi

    # TODO: Make a flag, something for the common implementation, that controls whether non-free software
    # can be used at all.
    if [ "$IS_METAL" != "0" -a "$KERNEL" = "Linux" -a "$DISTRO" = "Debian" ]; then
        echo "feature/zfs" # WARNING: Sets up the system for non-free software.
    fi
}

"${@}"
