#!/bin/sh

# Copyright (C) 2022 Keith "vorble"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# ALLOW_NONFREE
#
# This flag controls whether non-free software may be installed.
#
# 0 - Non-free software is NOT allowed (the default).
# 1 - Non-free software is allowed.

if [ "${ALLOW_NONFREE+x}" = "x" ]; then
    export ALLOW_NONFREE="${ALLOW_NONFREE}"
else
    export ALLOW_NONFREE=0
fi

if [ "$DEBUG" != "0" ]; then
    echo "ALLOW_NONFREE=$ALLOW_NONFREE"
fi

export ALLOW_NONFREE
