#!/bin/sh

# Copyright (C) 2022 Keith "vorble"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# ENABLE_HOOK_WATERMARK
#
# Values are 0 or 1. Default 0. Set to 1 to enable the `hook/watermark` hook,
# which makes a record of the setup process. See also `WATERMARK_DIR`.

if [ "${ENABLE_HOOK_WATERMARK+defined}" != "defined" ]; then
    ENABLE_HOOK_WATERMARK=0
fi

if [ "$DEBUG" != "0" ]; then
    echo "ENABLE_HOOK_WATERMARK=$ENABLE_HOOK_WATERMARK"
fi

export ENABLE_HOOK_WATERMARK
