#!/bin/sh

# Copyright (C) 2022 Keith "vorble"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# PATH_ENV
#
# A colon separated list of paths holding environment scripts that should be
# loaded.

if [ "${PATH_ENV+x}" = "x" ]; then
    export PATH_ENV="${PATH_ENV}"
else
    export PATH_ENV=
fi

if [ "$DEBUG" != "0" ]; then
    echo "PATH_ENV=$PATH_ENV"
fi

export PATH_ENV
