#!/bin/sh

# Copyright (C) 2022 Keith "vorble"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# PLZHELP
#
# Value is 0 or 1. Default to 0. Set this option to 0 for normal operation. Set
# this option to 1 to enable extra logging messages about things that might not
# be fully tested or finished in the software. Set this option if you would
# like to help improve the software.

if [ "${PLZHELP+defined}" != "defined" ]; then
    PLZHELP=0
fi

if [ "$DEBUG" != "0" ]; then
    echo "PLZHELP=$PLZHELP"
fi

export PLZHELP
