#!/bin/sh

# Copyright (C) 2022 Keith "vorble"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# WATERMARK_DIR
#
# Value is a path to a directory. Default to `/usr/local/etc/platform/`. Set
# this option to control where watermark files are stored which record the
# versions and loadouts used. See also `ENABLE_HOOK_WATERMARK`.

if [ "${WATERMARK_DIR+defined}" != "defined" ]; then
    WATERMARK_DIR=/usr/local/etc/platform
fi

if [ "$DEBUG" != "0" ]; then
    echo "WATERMARK_DIR=$WATERMARK_DIR"
fi

export WATERMARK_DIR
