#!/bin/sh

# ALLOW_NONFREE
#
# This flag controls whether non-free software may be installed.
#
# 0 - Non-free software is NOT allowed (the default).
# 1 - Non-free software is allowed.

if [ "${ALLOW_NONFREE+defined}" != "defined" ]; then
    ALLOW_NONFREE=0
fi

# NO DEBUG! This option is pre-included in vorble/loadout/base which can't make any output!

export ALLOW_NONFREE
