#!/bin/sh

set -eu

. include/user_exists
. include/maybe

list_features() {
    echo "feature/sudo"
}

post_install_hook() {
    for USER in $USERS; do
        if user_exists "$USER"; then
            if [ "$USER" != "root" ]; then
                maybe usermod -a -G sudo "$USER"
            fi
        fi
    done
}

"${@}"
