#!/bin/sh

set -eu

. include/maybe

list_features() {
    echo "feature/vim"
}

post_install_hook() {
    local USER HOMEDIR GROUP
    for USER in $USERS; do
        HOMEDIR="$( getent passwd "$USER" | cut -d: -f6 )"
        if [ -d "$HOMEDIR" ]; then
            GROUP="$USER"
            if [ "$USER" = "root" -a "$KERNEL" = "OpenBSD" ]; then
                GROUP=wheel
            fi
            maybe cp vorble/files/vimrc "$HOMEDIR/.vimrc"
            maybe chown "$USER:$GROUP" "$HOMEDIR/.vimrc"
        fi
    done
}

"${@}"
