#!/bin/sh

# Copyright (C) 2022 Keith "vorble"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -eu

. include/maybe

list_features() {
    echo "feature/vim"
}

post_install_hook() {
    local USER HOMEDIR GROUP
    for USER in $USERS; do
        HOMEDIR="$( getent passwd "$USER" | cut -d: -f6 )"
        if [ -d "$HOMEDIR" ]; then
            GROUP="$USER"
            if [ "$USER" = "root" -a "$KERNEL" = "OpenBSD" ]; then
                GROUP=wheel
            fi
            maybe cp vorble/files/vimrc "$HOMEDIR/.vimrc"
            maybe chown "$USER:$GROUP" "$HOMEDIR/.vimrc"
        fi
    done
}

"${@}"
