#!/bin/sh

set -eu

if [ "$ALLOW_NONFREE" = "0" ]; then
    echo "vorble/feature/zfs: ALLOW_NONFREE must be enabled for this feature." >&2
    exit 1
fi

. include/debian
. include/maybe

pre_install() {
    # TODO: CentOS?
    if [ "$KERNEL" != "Linux" -o "$DISTRO" != "Debian" ]; then
        echo "vorble/feature/zfs: Feature is currently only supported on Debian GNU/Linux." >&2
        exit 1
    fi

    local CURRENT_REPO
    CURRENT_REPO=`grep '^deb http' /etc/apt/sources.list | grep " ${DEBIAN_CODENAME} " | grep -o 'https\?:\/\/[^ ]\+'`
    if [ ! -f "/etc/apt/sources.list.d/${DEBIAN_CODENAME}-backports.list" ]; then
        echo "vorble/feature/zfs: Creating /etc/apt/sources.list.d/${DEBIAN_CODENAME}-backports.list"
        if [ "$DRY_RUN" = "0" ]; then
            cat > "/etc/apt/sources.list.d/${DEBIAN_CODENAME}-backports.list" <<EOF
deb ${CURRENT_REPO} ${DEBIAN_CODENAME}-backports main contrib non-free
deb-src ${CURRENT_REPO} ${DEBIAN_CODENAME}-backports main contrib non-free
EOF
        fi
    fi
}

list_packages() {
    echo "linux-headers-amd64"
}

post_install() {
    maybe apt-get update
    maybe apt-get install --yes "--target-release=${DEBIAN_CODENAME}-backports" zfsutils-linux
    maybe modprobe zfs
}

"${@}"
