#!/bin/sh

HAS_AMD_GRAPHICS=0

if [ "$KERNEL" = "Linux" ]; then
    if which lspci > /dev/null 2> /dev/null; then
        # Please list example matched lines here for various card models.
        # AMD Radeon RX 6600 XT
        #   0a:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 (rev c1)
        if lspci | grep 'VGA compatible controller' | grep -q AMD; then
            HAS_AMD_GRAPHICS=1
        fi
    else
        # TODO: CentOS. It doesn't come with lspci, so I would have to figure out how to check it from
        # files in /sys or something.
        echo "PLZHELP: env/HAS_AMD_GRAPHICS is not implemented for DISTRO=$DISTRO!"
    fi
else
    if [ "$PLZHELP" != "0" ]; then
        echo "PLZHELP: env/HAS_AMD_GRAPHICS is not implemented for KERNEL=$KERNEL!"
    fi
fi

if [ "$DEBUG" != "0" ]; then
    echo "HAS_AMD_GRAPHICS=$HAS_AMD_GRAPHICS"
fi

export HAS_AMD_GRAPHICS
