#!/bin/sh

# Lock the versions together since the main source code is packaged with this
# custom loadout.
export VORBLE_VERSION="$PLATFORM_VERSION"

if [ "$DEBUG" != "0" ]; then
    echo "VORBLE_VERSION=$VORBLE_VERSION"
fi
