#!/bin/sh

# Make VORBLE_VERSION equal to PLATFORM_VERSION since the main source code is
# maintained in parallel with this custom loadout.
export VORBLE_VERSION="$PLATFORM_VERSION"

if [ "$DEBUG" != "0" ]; then
    echo "VORBLE_VERSION=$VORBLE_VERSION"
fi
