#!/bin/bash

set -euo pipefail

function list_prerequisites() {
    echo "feature/zfs"
}

function list_features() {
    echo "feature/drivers"
    if [ "$IS_METAL" != "0" ]; then
        echo "feature/firmware"
    fi
    echo "feature/tools"
}

"${@}"
