#!/bin/sh

set -eu

list_prerequisites() {
    echo "feature/zfs"
}

list_features() {
    echo "feature/drivers"
    if [ "$IS_METAL" != "0" ]; then
        echo "feature/firmware"
    fi
    echo "feature/tools"
}

"${@}"
