#!/bin/sh

# Copyright (C) 2022 Keith "vorble"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. include/maybe

install_packages() {
    if [ "$#" = "0" ]; then
        return 0
    fi
    if [ "$PACKAGE_MANAGER" = "apt" ]; then
        maybe apt-get update
        maybe apt-get install --yes "${@}"
    elif [ "$PACKAGE_MANAGER" = "pkg_add" ]; then
        maybe pkg_add "${@}"
    elif [ "$PACKAGE_MANAGER" = "yum" ]; then
        maybe yum install -y "${@}"
    else
        echo "include/install_packages: install_packages() is not implemented for PACKAGE_MANAGER=$PACKAGE_MANAGER!" >&2
        exit 1
    fi
}
