#!/bin/sh

set -eu

install_packages() {
    # TODO: It makes more sense to keep track of the OS distribution and
    # version and choose the right package manager based on that, rather than
    # the kernel.
    if [ "$PACKAGE_MANAGER" = "apt" ]; then
        local INSTALL_COMMAND
        INSTALL_COMMAND="apt-get install --yes ${@}"
        echo $INSTALL_COMMAND
        if [ "$DRY_RUN" = "0" ]; then
            "${INSTALL_COMMAND}"
        fi
    else
        echo "include/install_packages: install_packages() is not implemented for PACKAGE_MANAGER=$PACKAGE_MANAGER!" >&2
        exit 1
    fi
}
