#!/bin/sh

# Copyright (C) 2022 Keith "vorble"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Print out the action to be performed and perform it. If DRY_RUN is set, the
# action is not performed.
#
# WATCH OUT! This is nice for conditionally executed activities, but it is
# problematic in several cases:
#
# * Don't use this in a pipe since it prints additional text to stdout when
#   is is run AND it does not print expected output when DRY_RUN is enabled.
# * Don't rely on the output to be properly quoted since the shell swallows
#   the quotes when it is called.

maybe() {
    printf '%s\n' "$*"
    if [ "$DRY_RUN" = "0" ]; then
        "${@}"
    fi
}
