#!/bin/sh

# Copyright (C) 2022 Keith "vorble"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Set a variable's value which can be later retrieved by var_get. Variables
# are not namespaced in any way, be careful of conflicting names.
#
# Usage:
#
#    var_set VARIABLE_NAME value
#
# Example:
#
#    var_set DOWNLOAD_FILE_NAME my-configuration-files.tar.gz

var_set() {
    printf '%s=' "$1" >> "$VAR_FILE"
    shift
    printf '%s\n' "$*" >> "$VAR_FILE"
}
