#!/bin/sh

# Copyright (C) 2022 Keith "vorble"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Get a variable's value which was previously set by var_set. Variables
# are not namespaced in any way, be careful of conflicting names. This
# function outputs the variable's value as text. Capture by using a
# sub-shell.
#
# Usage:
#
#    LOCAL_VALUE="$( var_get VARIABLE_NAME )"
#
# Example:
#
#    DOWNLOAD_FILE_NAME="$( var_get DOWNLOAD_FILE_NAME )"

var_get() {
    ( grep -e "^$1=" "$VAR_FILE" | tail -1 | sed 's/^[^=]*=//' ) || true
}
