#!/bin/sh

# Copyright (C) 2022 Keith "vorble"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

ARCH="$( arch )"

if [ "$ARCH" = "x86_64" ]; then
    ARCH="amd64" # Shorter than x86_64.
elif [ "$ARCH" = "amd64" ]; then
    : # Good.
elif [ "$ARCH" = "OpenBSD.amd64" ]; then
    ARCH="amd64"
elif [ "$ARCH" = "armv6l" ]; then
    : # Good.
elif [ "$ARCH" = "armv7l" ]; then
    : # Good.
else
    echo "env/ARCH: Unable to determine ARCH! Possible value $ARCH?" >&2
    exit 1
fi

if [ "$DEBUG" != "0" ]; then
    echo "ARCH=$ARCH"
fi

export ARCH
