#!/bin/sh

set -eu

if [ -f /proc/cpuinfo ]; then
    CPU_VENDOR=`cat /proc/cpuinfo | grep vendor_id | grep -o ':.*' | sed 's/^: //' | uniq | head -1`
elif [ -x /sbin/sysctl ]; then
    CPU_VENDOR=`/sbin/sysctl -n machdep.cpuvendor`
else
    echo "Unable to determine CPU vendor!" >&2
    exit 1
fi 

if [ "${CPU_VENDOR}" = "GenuineIntel" ]; then
    CPU_VENDOR=intel
elif [ "${CPU_VENDOR}" = "AuthenticAMD" ]; then
    CPU_VENDOR=amd
else
    echo "Unexpected CPU vendor ${CPU_VENDOR}!" >&2
    exit 1
fi

if [ "$DEBUG" != "0" ]; then
    echo "CPU_VENDOR=$CPU_VENDOR"
fi

export CPU_VENDOR
