#!/bin/sh

# Copyright (C) 2022 Keith "vorble"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -eu

if [ -f /proc/cpuinfo ]; then
    CPU_VENDOR=`cat /proc/cpuinfo | grep vendor_id | grep -o ':.*' | sed 's/^: //' | uniq | head -1`
elif [ -x /sbin/sysctl ]; then
    CPU_VENDOR=`/sbin/sysctl -n machdep.cpuvendor`
else
    echo "Unable to determine CPU vendor!" >&2
    exit 1
fi

if [ "${CPU_VENDOR}" = "GenuineIntel" ]; then
    CPU_VENDOR=intel
elif [ "${CPU_VENDOR}" = "AuthenticAMD" ]; then
    CPU_VENDOR=amd
else
    echo "Unexpected CPU vendor ${CPU_VENDOR}!" >&2
    exit 1
fi

if [ "$DEBUG" != "0" ]; then
    echo "CPU_VENDOR=$CPU_VENDOR"
fi

export CPU_VENDOR
