#!/bin/sh

# Copyright (C) 2022 Keith "vorble"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

DISTRO_VERSION=""

if [ -f /etc/os-release ]; then
    if grep -q 'PRETTY_NAME="Debian GNU/Linux 10 (buster)"' /etc/os-release; then
        DISTRO_VERSION="10"
    elif grep -q 'PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"' /etc/os-release; then
        DISTRO_VERSION="11"
    elif grep -q 'PRETTY_NAME="CentOS Linux 7 (Core)"' /etc/os-release; then
        DISTRO_VERSION="7"
    elif grep -q 'VERSION_ID=35' /etc/os-release; then
        DISTRO_VERSION="35"
    fi
fi

if uname -s -r | grep 'OpenBSD [0-9][0-9]*\.[0-9][0-9]*' > /dev/null; then
    DISTRO_VERSION="`uname -r`"
fi

if [ "$DISTRO_VERSION" = "" ]; then
    echo "env/DISTRO_VERSION: Unable to determine distro version." >&2
    exit 1
fi

if [ "$DEBUG" != "0" ]; then
    echo "DISTRO_VERSION=$DISTRO_VERSION"
fi

export DISTRO_VERSION
