#!/bin/sh

# Copyright (C) 2022 Keith "vorble"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

DISTRO=""

if [ -f /etc/os-release ]; then
    if grep -q 'NAME="Debian GNU/Linux"' /etc/os-release; then
      DISTRO="Debian"
    fi
fi

if uname -s | grep OpenBSD > /dev/null; then
    DISTRO="OpenBSD"
fi

if [ "$DISTRO" = "" ]; then
    echo "env/DISTRO: Unable to determine distro." >&2
    exit 1
fi

if [ "$DEBUG" != "0" ]; then
    echo "DISTRO=$DISTRO"
fi

export DISTRO
