#!/bin/sh

# Copyright (C) 2022 Keith "vorble"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

HAS_AMD_GRAPHICS=0

if [ "$KERNEL" = "Linux" ]; then
    # Please list example matched lines here for various card models.
    # AMD Radeon RX 6600 XT
    #   0a:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 (rev c1)
    if lspci | grep 'VGA compatible controller' | grep -q AMD; then
        HAS_AMD_GRAPHICS=1
    fi
else
    if [ "$PLZHELP" != "0" ]; then
        echo "PLZHELP: env/HAS_AMD_GRAPHICS is not implemented for KERNEL=$KERNEL!"
    fi
fi

if [ "$DEBUG" != "0" ]; then
    echo "HAS_AMD_GRAPHICS=$HAS_AMD_GRAPHICS"
fi

export HAS_AMD_GRAPHICS
