#!/bin/sh

# Copyright (C) 2022 Keith "vorble"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

HAS_NVIDIA_GRAPHICS=0

if [ "$KERNEL" = "Linux" ]; then
    if lspci | grep 'VGA compatible controller' | grep -q NVIDIA; then
        # 02:00.0 VGA compatible controller: NVIDIA Corporation GK106GL [Quadro K4000] (rev a1)
        HAS_NVIDIA_GRAPHICS=1
    fi
else
    if [ "$PLZHELP" != "0" ]; then
        echo "PLZHELP: env/HAS_NVIDIA_GRAPHICS is not implemented for KERNEL=$KERNEL!"
    fi
fi

if [ "$DEBUG" != "0" ]; then
    echo "HAS_NVIDIA_GRAPHICS=$HAS_NVIDIA_GRAPHICS"
fi

export HAS_NVIDIA_GRAPHICS
