#!/bin/sh

# Copyright (C) 2022 Keith "vorble"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

IS_METAL=1
if grep -q 'flags\s\+:.*\shypervisor\($\|\s\)' /proc/cpuinfo; then
    IS_METAL=0
fi

if [ "$DEBUG" != "0" ]; then
    echo "IS_METAL=$IS_METAL"
fi

export IS_METAL
