#!/bin/sh

# Copyright (C) 2022 Keith "vorble"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# PACKAGE_MANAGER
#
# The system's package manager. Values are `apt` (Debian), `yum`/`dnf`
# (CentOS/Fedora), `pkg_add` (OpenBSD), and `zypper` (openSUSE).

PACKAGE_MANAGER=""

if which apt-get > /dev/null 2> /dev/null; then
    PACKAGE_MANAGER="apt"
elif which pkg_add > /dev/null 2> /dev/null; then
    PACKAGE_MANAGER="pkg_add"
elif which dnf > /dev/null 2> /dev/null; then
    PACKAGE_MANAGER="dnf"
elif which yum > /dev/null 2> /dev/null; then
    PACKAGE_MANAGER="yum"
elif which zypper > /dev/null 2> /dev/null; then
    PACKAGE_MANAGER="zypper"
else
    echo "env/PACKAGE_MANAGER: Unable to determine package manager." >&2
    exit 1
fi

if [ "$DEBUG" != "0" ]; then
    echo "PACKAGE_MANAGER=$PACKAGE_MANAGER"
fi

export PACKAGE_MANAGER
