#!/bin/sh

# Copyright (C) 2022 Keith "vorble"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# PACKAGE_MANAGER
#
# The system's package manager. Values are `apt` (Debian), `yum`/`dnf`
# (CentOS/Fedora), `pkg_add` (OpenBSD), and `zypper` (openSUSE).

PACKAGE_MANAGER=""

if [ "$KERNEL" = "OpenBSD" ]; then
    PACKAGE_MANAGER="pkg_add"
elif [ "$KERNEL" = "Linux" ]; then
    if [ "$DISTRO" = "CentOS" ]; then
        if [ "$DISTRO_VERSION" -lt "8" ]; then
            PACKAGE_MANAGER="yum"
        else
            PACKAGE_MANAGER="dnf"
        fi
    elif [ "$DISTRO" = "Debian" ]; then
        PACKAGE_MANAGER="apt"
    elif [ "$DISTRO" = "Fedora" ]; then
        PACKAGE_MANAGER="dnf"
    elif [ "$DISTRO" = "openSUSE" ]; then
        PACKAGE_MANAGER="zypper"
    fi
fi

if [ "$PACKAGE_MANAGER" = "" ]; then
    echo "env/PACKAGE_MANAGER: Unable to determine package manager." >&2
    exit 1
fi

if [ "$DEBUG" != "0" ]; then
    echo "PACKAGE_MANAGER=$PACKAGE_MANAGER"
fi

export PACKAGE_MANAGER
