#!/bin/sh

# Copyright (C) 2022 Keith "vorble"
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -eu

if [ "$DISTRO" != "CentOS" ]; then
    echo "feature/centos/powertools: For use on CentOS 8 and later." >&2
    exit 1
elif [ "$DISTRO_VERSION" -lt "8" ]; then
    echo "feature/centos/powertools: For use on CentOS 8 and later." >&2
    exit 1
fi

install() {
    dnf config-manager --set-enabled powertools
}

"${@}"
